[I 160524 13:06:42 web:1825] 200 POST http://oth.str.mdt.qq.com:8080/analytics/upload (192.168.56.101) 320.20ms
[I 160524 13:06:44 web:1825] 200 POST http://astrategy.beacon.qq.com:8080/analytics/upload?mType=beacon?sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 493.73ms
[I 160524 13:06:45 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 363.97ms
[I 160524 13:06:45 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 277.80ms
[I 160524 13:06:45 web:1825] 200 POST http://astrategy.beacon.qq.com:8080/analytics/upload?mType=beacon?sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 306.76ms
[I 160524 13:06:46 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=be2ef427059e01bb&sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 235.16ms
[I 160524 13:06:46 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=ae88b863139c7679&sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 419.01ms
[I 160524 13:06:49 web:1825] 200 POST http://astrategy.beacon.qq.com:8080/analytics/upload?mType=beacon?sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 358.00ms
[I 160524 13:06:49 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=89fc990e9a86e74f&sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 375.77ms
[I 160524 13:06:50 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=24e825fa390af02a&sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 432.90ms
[I 160524 13:06:51 web:1825] 200 POST http://astrategy.beacon.qq.com:8080/analytics/upload?mType=beacon?sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 385.04ms
[I 160524 13:07:20 web:1825] 200 POST http://astrategy.beacon.qq.com:8080/analytics/upload?mType=beacon?sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 5420.60ms
[I 160524 13:07:20 web:1825] 200 POST http://astrategy.beacon.qq.com:8080/analytics/upload?mType=beacon?sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 248.31ms
[I 160524 13:07:36 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 8145.51ms
[I 160524 13:07:37 web:1825] 200 POST http://astrategy.beacon.qq.com:8080/analytics/upload?mType=beacon?sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 261.45ms
[I 160524 13:07:37 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=82768e829820ce16&sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 320.49ms
[I 160524 13:07:37 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=0786bb7aa7138e76&sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 266.05ms
[I 160524 13:08:36 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=2d57596b67016379&sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 236.06ms
[I 160524 13:08:36 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=9e6871e2f40c290f&sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 419.02ms
[E 160524 13:08:43 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:08:43 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'User-Agent': 'Android-GData-Contacts/1.3 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:08:43 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127279.23ms
[I 160524 13:09:16 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=cb035b26a51a0e72&sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 239.94ms
[I 160524 13:09:16 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=e0b8250df60a15bf&sid=0527926ff2786278ee04e29c220e6f9e (192.168.56.101) 7843.49ms
[I 160524 13:09:17 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 461.49ms
[E 160524 13:09:40 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:09:40 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:09:40 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:09:40 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127205.85ms
[E 160524 13:09:40 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:09:40 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127210.55ms
[I 160524 13:09:50 web:1825] 200 GET http://dldir1.qq.com/qqfile/qd/RegDevLockCfg.xml?mType=ConfigCheck (192.168.56.101) 5262.63ms
[E 160524 13:10:17 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:10:17 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'User-Agent': 'Android-GData-Contacts/1.3 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:10:17 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127326.73ms
[E 160524 13:10:28 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:10:28 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:10:28 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127341.74ms
[E 160524 13:10:38 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:10:38 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:10:38 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127280.62ms
[E 160524 13:10:58 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:10:58 web:1421] Uncaught exception CONNECT www.googleapis.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='www.googleapis.com', method='CONNECT', uri='www.googleapis.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'www.googleapis.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'DroidGuard/8489000 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:10:58 web:1825] 500 CONNECT www.googleapis.com:443 (192.168.56.101) 127279.33ms
[E 160524 13:11:08 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:11:08 web:1421] Uncaught exception CONNECT www.googleapis.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='www.googleapis.com', method='CONNECT', uri='www.googleapis.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'www.googleapis.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'DroidGuard/8489000 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:11:08 web:1825] 500 CONNECT www.googleapis.com:443 (192.168.56.101) 127866.21ms
[E 160524 13:11:33 concurrent:122] Future exception was never retrieved: gaierror: [Errno -2] Name or service not known
[E 160524 13:11:33 web:1421] Uncaught exception CONNECT play.googleapis.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='play.googleapis.com', method='CONNECT', uri='play.googleapis.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'play.googleapis.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'Android-Finsky/6.0.5'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:11:33 web:1825] 500 CONNECT play.googleapis.com:443 (192.168.56.101) 15495.81ms
[E 160524 13:11:48 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:11:48 web:1421] Uncaught exception CONNECT www.googleapis.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='www.googleapis.com', method='CONNECT', uri='www.googleapis.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'www.googleapis.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'DroidGuard/8489000 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:11:48 web:1825] 500 CONNECT www.googleapis.com:443 (192.168.56.101) 127180.75ms
[E 160524 13:11:58 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:11:58 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H)'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:11:58 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127179.22ms
[E 160524 13:11:58 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:12:07 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:12:07 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:12:07 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127202.37ms
[E 160524 13:12:13 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:12:13 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'Dalvik/1.6.0 (Linux; U; Android 4.4.2; Samsung Galaxy S4 - 4.4.2 - API 19 - 1080x1920 Build/KOT49H)'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:12:13 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127320.19ms
[E 160524 13:12:41 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:12:41 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'Android-GData/1.1 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:12:41 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127192.61ms
[E 160524 13:12:48 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:12:48 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H)'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 305, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:12:48 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127302.50ms
[E 160524 13:57:31 web:1825] 599 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 10270.33ms
[I 160524 13:57:31 web:1825] 200 POST http://oth.str.mdt.qq.com:8080/analytics/upload (192.168.56.101) 15460.40ms
[I 160524 13:57:31 web:1825] 200 POST http://oth.str.mdt.qq.com:8080/analytics/upload (192.168.56.101) 10466.99ms
[I 160524 13:57:31 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 262.48ms
[I 160524 13:57:31 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 254.84ms
[I 160524 13:57:33 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 263.78ms
[I 160524 13:57:36 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 427.67ms
[I 160524 13:57:36 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 15366.25ms
[I 160524 13:57:39 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 341.21ms
[I 160524 13:57:48 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 1878.18ms
[I 160524 13:57:48 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 6882.32ms
[I 160524 13:57:48 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 469.85ms
[I 160524 13:57:56 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 883.11ms
[I 160524 13:58:01 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 689.82ms
[I 160524 13:58:10 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 735.65ms
[I 160524 13:59:11 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 437.94ms
[E 160524 13:59:22 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 13:59:22 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'User-Agent': 'Android-GData-Contacts/1.3 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 13:59:22 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 132361.13ms
[E 160524 13:59:33 web:1825] 599 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 10456.89ms
[I 160524 13:59:47 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 1823.31ms
[I 160524 13:59:48 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 727.93ms
[I 160524 13:59:49 web:1825] 200 POST http://oth.str.mdt.qq.com:8080/analytics/upload (192.168.56.101) 4459.46ms
[I 160524 14:00:12 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 7857.12ms
[E 160524 14:00:16 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:00:16 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:00:16 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 132345.94ms
[E 160524 14:00:17 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:00:17 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:00:17 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 128073.07ms
[I 160524 14:00:26 web:1825] 200 GET http://dldir1.qq.com/qqfile/qd/RegDevLockCfg.xml?mType=ConfigCheck (192.168.56.101) 1426.87ms
[E 160524 14:00:49 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:00:49 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'User-Agent': 'Android-GData-Contacts/1.3 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:00:49 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127336.82ms
[E 160524 14:01:01 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:01:01 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:01:01 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127340.82ms
[E 160524 14:01:11 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:01:11 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:01:11 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127335.32ms
[E 160524 14:01:40 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:01:40 web:1421] Uncaught exception CONNECT www.googleapis.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='www.googleapis.com', method='CONNECT', uri='www.googleapis.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'www.googleapis.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'DroidGuard/8489000 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:01:40 web:1825] 500 CONNECT www.googleapis.com:443 (192.168.56.101) 127295.25ms
[E 160524 14:01:47 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:01:47 web:1421] Uncaught exception CONNECT www.googleapis.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='www.googleapis.com', method='CONNECT', uri='www.googleapis.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'www.googleapis.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'DroidGuard/8489000 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:01:47 web:1825] 500 CONNECT www.googleapis.com:443 (192.168.56.101) 127317.30ms
[I 160524 14:01:56 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 317.54ms
[I 160524 14:02:05 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 398.29ms
[E 160524 14:02:22 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:02:22 web:1421] Uncaught exception CONNECT www.googleapis.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='www.googleapis.com', method='CONNECT', uri='www.googleapis.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'www.googleapis.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'DroidGuard/8489000 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:02:22 web:1825] 500 CONNECT www.googleapis.com:443 (192.168.56.101) 127388.50ms
[E 160524 14:02:33 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:02:33 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H)'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:02:33 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127545.69ms
[E 160524 14:02:41 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:02:41 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:02:41 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127275.10ms
[E 160524 14:02:47 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:02:52 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:02:52 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'Dalvik/1.6.0 (Linux; U; Android 4.4.2; Samsung Galaxy S4 - 4.4.2 - API 19 - 1080x1920 Build/KOT49H)'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:02:52 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127419.20ms
[E 160524 14:03:14 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:03:14 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'Android-GData/1.1 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:03:14 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127338.05ms
[E 160524 14:03:23 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:03:23 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H)'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:03:23 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 128212.88ms
[E 160524 14:14:37 concurrent:122] Future exception was never retrieved: gaierror: [Errno -3] Temporary failure in name resolution
[E 160524 14:15:17 web:1825] 599 POST http://oth.str.mdt.qq.com:8080/analytics/upload (192.168.56.101) 40037.10ms
[E 160524 14:15:17 web:1825] 599 POST http://oth.str.mdt.qq.com:8080/analytics/upload (192.168.56.101) 20021.03ms
[I 160524 14:16:42 web:1825] 200 POST http://oth.str.mdt.qq.com:8080/analytics/upload (192.168.56.101) 796.41ms
[I 160524 14:17:02 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 473.51ms
[I 160524 14:17:02 web:1825] 200 POST http://oth.str.mdt.qq.com:8080/analytics/upload (192.168.56.101) 298.24ms
[I 160524 14:17:09 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 6454.72ms
[I 160524 14:17:09 web:1825] 200 POST http://astrategy.beacon.qq.com:8080/analytics/upload?mType=beacon?sid=c207b8896039365b88a4df6305c4379f (192.168.56.101) 6378.42ms
[I 160524 14:17:09 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=cbcfd312fad55a61&sid=c207b8896039365b88a4df6305c4379f (192.168.56.101) 234.71ms
[I 160524 14:17:09 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=e175aff9b82f02ce&sid=c207b8896039365b88a4df6305c4379f (192.168.56.101) 228.91ms
[I 160524 14:17:09 web:1825] 200 POST http://oth.str.mdt.qq.com:8080/analytics/upload (192.168.56.101) 266.11ms
[I 160524 14:17:17 web:1825] 200 GET http://dldir1.qq.com/qqfile/qd/RegDevLockCfg.xml?mType=ConfigCheck (192.168.56.101) 203.92ms
[E 160524 14:17:24 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:17:24 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:17:24 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127290.60ms
[E 160524 14:17:25 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:17:25 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:17:25 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127298.00ms
[E 160524 14:17:56 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:17:56 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'User-Agent': 'Android-GData-Contacts/1.3 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:17:56 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127331.49ms
[E 160524 14:18:14 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:18:14 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:18:14 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127258.41ms
[E 160524 14:18:24 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:18:24 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:18:24 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127229.90ms
[E 160524 14:18:45 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:18:45 web:1421] Uncaught exception CONNECT www.googleapis.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='www.googleapis.com', method='CONNECT', uri='www.googleapis.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'www.googleapis.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'DroidGuard/8489000 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:18:45 web:1825] 500 CONNECT www.googleapis.com:443 (192.168.56.101) 127265.23ms
[E 160524 14:18:57 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:18:57 web:1421] Uncaught exception CONNECT www.googleapis.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='www.googleapis.com', method='CONNECT', uri='www.googleapis.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'www.googleapis.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'DroidGuard/8489000 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:18:57 web:1825] 500 CONNECT www.googleapis.com:443 (192.168.56.101) 127680.93ms
[I 160524 14:19:25 web:1825] 200 POST http://astrategy.beacon.qq.com:8080/analytics/upload?mType=beacon?sid=c207b8896039365b88a4df6305c4379f (192.168.56.101) 280.38ms
[I 160524 14:19:26 web:1825] 200 POST http://astrategy.beacon.qq.com:8080/analytics/upload?mType=beacon?sid=c207b8896039365b88a4df6305c4379f (192.168.56.101) 370.30ms
[I 160524 14:19:26 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=fb70ababeceb6261&sid=c207b8896039365b88a4df6305c4379f (192.168.56.101) 243.33ms
[E 160524 14:19:35 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:19:35 web:1421] Uncaught exception CONNECT www.googleapis.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='www.googleapis.com', method='CONNECT', uri='www.googleapis.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'www.googleapis.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'DroidGuard/8489000 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:19:35 web:1825] 500 CONNECT www.googleapis.com:443 (192.168.56.101) 127286.77ms
[E 160524 14:19:45 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:19:45 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H)'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:19:45 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127293.84ms
[E 160524 14:19:49 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:19:49 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:19:49 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127207.01ms
[E 160524 14:20:03 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:20:03 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'Dalvik/1.6.0 (Linux; U; Android 4.4.2; Samsung Galaxy S4 - 4.4.2 - API 19 - 1080x1920 Build/KOT49H)'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:20:03 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 132295.88ms
[E 160524 14:20:25 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:20:25 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'Android-GData/1.1 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:20:25 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127288.37ms
[I 160524 14:24:17 web:1825] 200 POST http://oth.str.mdt.qq.com:8080/analytics/upload (192.168.56.101) 15445.47ms
[I 160524 14:24:17 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 330.73ms
[I 160524 14:24:17 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 258.88ms
[I 160524 14:24:17 web:1825] 200 POST http://oth.str.mdt.qq.com:8080/analytics/upload (192.168.56.101) 269.37ms
[I 160524 14:24:17 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 278.38ms
[I 160524 14:24:17 web:1825] 200 POST http://oth.str.mdt.qq.com:8080/analytics/upload (192.168.56.101) 256.94ms
[I 160524 14:24:17 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 248.61ms
[I 160524 14:24:17 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 420.40ms
[I 160524 14:24:18 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 439.42ms
[I 160524 14:24:21 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 325.41ms
[I 160524 14:24:28 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 5277.19ms
[I 160524 14:24:28 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 234.93ms
[I 160524 14:24:29 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 632.63ms
[I 160524 14:24:32 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 296.81ms
[I 160524 14:24:37 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 325.23ms
[I 160524 14:24:50 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 333.44ms
[I 160524 14:24:51 web:1825] 200 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 235.81ms
[I 160524 14:24:52 web:1825] 200 POST http://oth.str.mdt.qq.com:8080/analytics/upload (192.168.56.101) 261.90ms
[I 160524 14:24:53 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=e9818f9f1661ab35&sid=15bf40cfe20fee5d898646db49aff460 (192.168.56.101) 247.12ms
[I 160524 14:24:53 web:1825] 200 POST http://astrategy.beacon.qq.com:8080/analytics/upload?mType=beacon?sid=15bf40cfe20fee5d898646db49aff460 (192.168.56.101) 519.66ms
[I 160524 14:24:53 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=93770da5764dff66&sid=15bf40cfe20fee5d898646db49aff460 (192.168.56.101) 448.06ms
[I 160524 14:24:54 web:1825] 200 POST http://astrategy.beacon.qq.com:8080/analytics/upload?mType=beacon?sid=15bf40cfe20fee5d898646db49aff460 (192.168.56.101) 344.69ms
[I 160524 14:25:41 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=0c791797f8f9ba98&sid=15bf40cfe20fee5d898646db49aff460 (192.168.56.101) 1154.11ms
[E 160524 14:25:55 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:25:55 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'User-Agent': 'Android-GData-Contacts/1.3 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:25:55 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127271.85ms
[I 160524 14:26:33 web:1825] 200 POST http://aeventlog.beacon.qq.com:8080/analytics/upload?mType=beacon?rid=b6b96812566a580e&sid=15bf40cfe20fee5d898646db49aff460 (192.168.56.101) 625.52ms
[E 160524 14:26:55 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:26:55 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:26:55 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:26:55 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 132731.53ms
[E 160524 14:26:55 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:26:55 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127726.14ms
[I 160524 14:26:55 web:1825] 200 GET http://dldir1.qq.com/qqfile/qd/RegDevLockCfg.xml?mType=ConfigCheck (192.168.56.101) 5073.46ms
[E 160524 14:27:33 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:27:33 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'User-Agent': 'Android-GData-Contacts/1.3 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:27:33 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 132174.81ms
[E 160524 14:27:40 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:27:40 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:27:40 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127301.50ms
[E 160524 14:27:50 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:27:50 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:27:50 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127190.79ms
[E 160524 14:28:12 web:1421] Uncaught exception POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101)
    HTTPServerRequest(protocol='http', host='monitor.uu.qq.com', method='POST', uri='http://monitor.uu.qq.com/analytics/rqdsync', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Content-Length': '394', 'A37': 'wifi', 'Bid': 'com.tencent.mobileqq', 'A38': 'wifi', 'Pid': 'com.tencent.mobileqq', 'Wup_version': '3.0', 'Host': 'monitor.uu.qq.com', 'Pver': '6.3.3.358'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1498, in future_complete
        f.result()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/gen.py", line 812, in run
        yielded = self.gen.send(value)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 236, in get
        self.finish_response(response)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 164, in finish_response
        self.set_header(header, value)
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 324, in set_header
        self._headers[name] = self._convert_header_value(value)
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 362, in _convert_header_value
        raise ValueError("Unsafe header value %r", value)
    ValueError: ('Unsafe header value %r', 'http://www.139nav.com/err\x00')
[E 160524 14:28:12 web:1825] 500 POST http://monitor.uu.qq.com/analytics/rqdsync (192.168.56.101) 10109.65ms
[E 160524 14:28:16 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:28:16 web:1421] Uncaught exception CONNECT www.googleapis.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='www.googleapis.com', method='CONNECT', uri='www.googleapis.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'www.googleapis.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'DroidGuard/8489000 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:28:16 web:1825] 500 CONNECT www.googleapis.com:443 (192.168.56.101) 127296.00ms
[E 160524 14:28:20 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:28:20 web:1421] Uncaught exception CONNECT www.googleapis.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='www.googleapis.com', method='CONNECT', uri='www.googleapis.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'www.googleapis.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'DroidGuard/8489000 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:28:20 web:1825] 500 CONNECT www.googleapis.com:443 (192.168.56.101) 127227.87ms
[E 160524 14:29:10 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:29:10 web:1421] Uncaught exception CONNECT www.googleapis.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='www.googleapis.com', method='CONNECT', uri='www.googleapis.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'www.googleapis.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'DroidGuard/8489000 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:29:10 web:1825] 500 CONNECT www.googleapis.com:443 (192.168.56.101) 132184.10ms
[E 160524 14:29:16 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:29:20 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:29:20 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H)'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:29:20 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127229.75ms
[E 160524 14:29:20 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:29:20 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'Android-GData/1.1 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:29:20 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127342.61ms
[E 160524 14:29:20 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:29:20 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'GoogleAuth/1.4 (mobsec KOT49H); gzip'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:29:20 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 127292.59ms
[E 160524 14:29:42 concurrent:122] Future exception was never retrieved: StreamClosedError
[E 160524 14:30:02 concurrent:122] Future exception was never retrieved: gaierror: [Errno -3] Temporary failure in name resolution
[E 160524 14:30:22 concurrent:122] Future exception was never retrieved: gaierror: [Errno -3] Temporary failure in name resolution
[E 160524 14:30:42 concurrent:122] Future exception was never retrieved: gaierror: [Errno -3] Temporary failure in name resolution
[E 160524 14:31:02 concurrent:122] Future exception was never retrieved: gaierror: [Errno -3] Temporary failure in name resolution
[E 160524 14:31:17 web:1421] Uncaught exception CONNECT android.clients.google.com:443 (192.168.56.101)
    HTTPServerRequest(protocol='http', host='android.clients.google.com', method='CONNECT', uri='android.clients.google.com:443', version='HTTP/1.1', remote_ip='192.168.56.101', headers={'Host': 'android.clients.google.com', 'Proxy-Connection': 'Keep-Alive', 'User-Agent': 'Dalvik/1.6.0 (Linux; U; Android 4.4.2; Samsung Galaxy S4 - 4.4.2 - API 19 - 1080x1920 Build/KOT49H)'})
    Traceback (most recent call last):
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/marine/APKAnalyserModules/DynamicAnalysis/WebProxy/pyWebProxy/pywebproxy.py", line 304, in ssl_fail
        self.request.connection.stream.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 356, in write
        self._check_closed()
      File "/home/marine/.local/lib/python2.7/site-packages/tornado/iostream.py", line 864, in _check_closed
        raise StreamClosedError("Stream is closed")
    StreamClosedError: Stream is closed
[E 160524 14:31:17 web:1825] 500 CONNECT android.clients.google.com:443 (192.168.56.101) 239235.41ms
